<a href="https://colab.research.google.com/github/AryanSai/Deep-Learning/blob/main/DataCamp_Experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensors

In [1]:
import torch

In [2]:
lis=[[[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]]]
tenso = torch.tensor(lis)

In [3]:
print(tenso.shape)
print(tenso.device)

torch.Size([2, 5, 3])
cpu


In [4]:
import numpy as np
nparray = np.array(lis)
print(nparray.shape)

(2, 5, 3)


In [5]:
tens1=torch.from_numpy(nparray)

In [6]:
print(tens1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])


In [7]:
l=[1,2,3]
t=torch.tensor(l)
print(t.shape)
print(t)

torch.Size([3])
tensor([1, 2, 3])


In [8]:
l=[[1,2,3]]
t=torch.tensor(l)
print(t.shape)
print(t)

torch.Size([1, 3])
tensor([[1, 2, 3]])


##Neural Networks

In [9]:
import torch.nn as nn

input = torch.tensor([[1.1,2.0,3.0],[1.1,2.0,3.0]]) #should be floats

print(input)

linear_layer = nn.Linear(in_features=3, out_features=2)

output=linear_layer(input)

print(output)

tensor([[1.1000, 2.0000, 3.0000],
        [1.1000, 2.0000, 3.0000]])
tensor([[ 0.1061, -1.1227],
        [ 0.1061, -1.1227]], grad_fn=<AddmmBackward0>)


In [10]:
print(linear_layer.weight)
print(linear_layer.bias)

Parameter containing:
tensor([[ 0.1771,  0.4442, -0.2755],
        [-0.2658, -0.0509, -0.1373]], requires_grad=True)
Parameter containing:
tensor([-0.1507, -0.3167], requires_grad=True)


In [11]:
model = nn.Sequential(
    nn.Linear(3,2),
    nn.Linear(2,1)
)

output=model(input)
print(output)

tensor([[0.7934],
        [0.7934]], grad_fn=<AddmmBackward0>)


##Activation Functions

In [12]:
model = nn.Sequential(
    nn.Linear(3,2),
    nn.Linear(2,1),
    nn.Sigmoid()
)

output=model(input)
print(output)

tensor([[0.4894],
        [0.4894]], grad_fn=<SigmoidBackward0>)


In [13]:
model = nn.Sequential(
    nn.Linear(3,2),
    nn.Softmax()
)

output=model(input)
print(output)

tensor([[0.8761, 0.1239],
        [0.8761, 0.1239]], grad_fn=<SoftmaxBackward0>)


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1736: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [14]:
m = nn.Softmax(dim=0)

# If dim=0: Softmax is applied across rows. Each column's elements will sum to 1.

input = torch.tensor([[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]])

output = m(input)
print(output)

        # sum =1
#tensor([[0.5000, 0.5000, 0.5000],
        # [0.5000, 0.5000, 0.5000]])

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])


In [15]:
m = nn.Softmax(dim=1)

# If dim=1: Softmax is applied across columns. Each row's elements will sum to 1.

input = torch.tensor([[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]])

output = m(input)
print(output)

# tensor([[0.0900, 0.2447, 0.6652],    # sum =1
        # [0.0900, 0.2447, 0.6652]])

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


In [16]:
m = nn.Softmax(dim=-1)

input = torch.tensor([[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]])

output = m(input)
print(output)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


In [17]:
print(input.shape)

torch.Size([2, 3])


In [18]:
input = torch.tensor([[[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]],[[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]]])

print("Shape: ", input.shape)

m = nn.Softmax(dim=0)
output = m(input)
print(output)

m = nn.Softmax(dim=1)
output = m(input)
print(output)

m = nn.Softmax(dim=2)
output = m(input)
print(output)

m = nn.Softmax(dim=-1)
output = m(input)
print(output)

Shape:  torch.Size([2, 2, 3])
tensor([[[0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000]]])
tensor([[[0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000]]])
tensor([[[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]],

        [[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]]])
tensor([[[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]],

        [[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]]])


In [19]:
input=torch.randn(2,3,4)
print(input)

tensor([[[ 1.3024,  1.6707, -0.3700, -0.2300],
         [ 1.0639, -0.1652, -1.9012,  0.2143],
         [ 0.4107,  0.8822, -0.5475,  0.6556]],

        [[-0.9559,  1.1679, -0.8316,  1.3750],
         [ 0.0210,  0.4599,  0.1337, -0.2866],
         [-1.2827,  1.5552, -0.6034, -1.2019]]])


In [21]:
print(torch.tensor(1))
print(torch.tensor(0))

tensor(1)
tensor(0)


In [25]:
import torch.nn.functional as F

print(
F.one_hot(torch.tensor(0),num_classes=3),
F.one_hot(torch.tensor(1),num_classes=3),
F.one_hot(torch.tensor(2),num_classes=3))

tensor([1, 0, 0]) tensor([0, 1, 0]) tensor([0, 0, 1])


##Cross Entropy Loss

In [33]:
from torch.nn import CrossEntropyLoss

scores = torch.rand(2,2)
print(scores)

one=F.one_hot(torch.tensor(0),num_classes=2)
print(one)

loss = CrossEntropyLoss()

loss(scores,one)

tensor([[0.1115, 0.9939],
        [0.6521, 0.2267]])
tensor([1, 0])


tensor(0.4246)