In [1]:
import torch
torch.__version__

/Users/aryansai/Documents/Deep-Learning/myenv/lib/python3.13/site-packages/torch/_subclasses/functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


'2.7.0'

In [2]:
#scalar
scalar =  torch.tensor(6)
print(scalar)
print(scalar.ndim)

tensor(6)
0


You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

In [3]:
vector = torch.tensor([1,2,3])
print(vector)
print(vector.ndim)
print(vector.size())
print(vector.shape)

tensor([1, 2, 3])
1
torch.Size([3])
torch.Size([3])


In [4]:
matrix = torch.tensor([[1,2],[3,4]])
print(matrix)
print(matrix.ndim)
print(matrix.size())
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])
torch.Size([2, 2])


In [5]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
print(TENSOR.ndim)
print(TENSOR.size())
print(TENSOR.shape)

3
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])


In [6]:
rand_tensor = torch.rand(2,3)
print(rand_tensor)
print(rand_tensor.ndim)
print(rand_tensor.size())
print(rand_tensor.shape)
print(rand_tensor.dtype)

tensor([[0.3757, 0.6639, 0.5830],
        [0.6266, 0.2649, 0.6989]])
2
torch.Size([2, 3])
torch.Size([2, 3])
torch.float32


In [7]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [8]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [9]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])